apiVersion: v1
kind: Service
metadata:
  name: amazon-app-service
  labels:
    app: amazon-app
spec:
  type: NodePort
  selector:
    app: amazon-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007